/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as TransactionsRouteImport } from "./routes/transactions"
import { Route as SendTokenRouteImport } from "./routes/send-token"
import { Route as AddTokenRouteImport } from "./routes/add-token"
import { Route as IndexRouteImport } from "./routes/index"

const TransactionsRoute = TransactionsRouteImport.update({
  id: "/transactions",
  path: "/transactions",
  getParentRoute: () => rootRouteImport,
} as any)
const SendTokenRoute = SendTokenRouteImport.update({
  id: "/send-token",
  path: "/send-token",
  getParentRoute: () => rootRouteImport,
} as any)
const AddTokenRoute = AddTokenRouteImport.update({
  id: "/add-token",
  path: "/add-token",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/add-token": typeof AddTokenRoute
  "/send-token": typeof SendTokenRoute
  "/transactions": typeof TransactionsRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/add-token": typeof AddTokenRoute
  "/send-token": typeof SendTokenRoute
  "/transactions": typeof TransactionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/add-token": typeof AddTokenRoute
  "/send-token": typeof SendTokenRoute
  "/transactions": typeof TransactionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/add-token" | "/send-token" | "/transactions"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/add-token" | "/send-token" | "/transactions"
  id: "__root__" | "/" | "/add-token" | "/send-token" | "/transactions"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddTokenRoute: typeof AddTokenRoute
  SendTokenRoute: typeof SendTokenRoute
  TransactionsRoute: typeof TransactionsRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/transactions": {
      id: "/transactions"
      path: "/transactions"
      fullPath: "/transactions"
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/send-token": {
      id: "/send-token"
      path: "/send-token"
      fullPath: "/send-token"
      preLoaderRoute: typeof SendTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/add-token": {
      id: "/add-token"
      path: "/add-token"
      fullPath: "/add-token"
      preLoaderRoute: typeof AddTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddTokenRoute: AddTokenRoute,
  SendTokenRoute: SendTokenRoute,
  TransactionsRoute: TransactionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
