// Auto-generated file - do not edit manually
// This file is generated by error-extractor.ts
// Run: npm run extract:errors

export const ERROR_MAP: Record<
    string,
    Record<number, { constantName: string; errorMessage: string }>
> = {
    access: {
        "0": {
            constantName: "ECharacterTransfer",
            errorMessage: "Character cannot be transferred",
        },
    },
    assembly: {
        "0": {
            constantName: "EAssemblyTypeIdEmpty",
            errorMessage: "Assembly TypeId is empty",
        },
        "1": {
            constantName: "EAssemblyItemIdEmpty",
            errorMessage: "Assembly ItemId is empty",
        },
        "2": {
            constantName: "EAssemblyAlreadyExists",
            errorMessage: "Assembly with this ItemId already exists",
        },
        "3": {
            constantName: "EAssemblyNotAuthorized",
            errorMessage: "Assembly access not authorized",
        },
        "4": {
            constantName: "ENetworkNodeDoesNotExist",
            errorMessage:
                "Provided network node does not match the assembly's configured energy source",
        },
        "5": {
            constantName: "EAssemblyOnline",
            errorMessage: "Assembly should be offline",
        },
    },
    metadata: {
        "0": {
            constantName: "ENotAuthorized",
            errorMessage: "Not authorized to update metadata",
        },
    },
    storage_unit: {
        "0": {
            constantName: "EStorageUnitTypeIdEmpty",
            errorMessage: "StorageUnit TypeId is empty",
        },
        "1": {
            constantName: "EStorageUnitItemIdEmpty",
            errorMessage: "StorageUnit ItemId is empty",
        },
        "2": {
            constantName: "EStorageUnitAlreadyExists",
            errorMessage: "StorageUnit with the same Item Id already exists",
        },
        "3": {
            constantName: "EAssemblyNotAuthorized",
            errorMessage: "StorageUnit access not authorized",
        },
        "4": {
            constantName: "EExtensionNotAuthorized",
            errorMessage: "Access only authorized for the custom contract of the registered type",
        },
        "5": {
            constantName: "EInventoryNotAuthorized",
            errorMessage: "Inventory Access not authorized",
        },
        "6": {
            constantName: "ENotOnline",
            errorMessage: "Storage Unit is not online",
        },
        "7": {
            constantName: "ETenantMismatch",
            errorMessage: "Item cannot be transferred across tenants",
        },
        "8": {
            constantName: "EUnauthorizedSponsor",
            errorMessage: "Unauthorized sponsor",
        },
        "9": {
            constantName: "ETransactionNotSponsored",
            errorMessage: "Transaction not sponsored",
        },
        "10": {
            constantName: "ENetworkNodeMismatch",
            errorMessage:
                "Provided network node does not match the storage unit's configured energy source",
        },
        "11": {
            constantName: "EStorageUnitInvalidState",
            errorMessage: "Storage Unit should be offline",
        },
    },
    character: {
        "0": {
            constantName: "EGameCharacterIdEmpty",
            errorMessage: "Game character ID is empty",
        },
        "1": {
            constantName: "ETribeIdEmpty",
            errorMessage: "Tribe ID is empty",
        },
        "2": {
            constantName: "ECharacterAlreadyExists",
            errorMessage: "Character with this game character ID already exists",
        },
        "3": {
            constantName: "ETenantEmpty",
            errorMessage: "Tenant name cannot be empty",
        },
        "4": {
            constantName: "EAddressEmpty",
            errorMessage: "Address cannot be empty",
        },
    },
    sig_verify: {
        "0": {
            constantName: "EInvalidPublicKeyLen",
            errorMessage: "Invalid public key length",
        },
        "1": {
            constantName: "EUnsupportedScheme",
            errorMessage: "Unsupported scheme",
        },
        "2": {
            constantName: "EInvalidLen",
            errorMessage: "Invalid length",
        },
    },
    network_node: {
        "0": {
            constantName: "ENetworkNodeTypeIdEmpty",
            errorMessage: "Network Node TypeId is empty",
        },
        "1": {
            constantName: "ENetworkNodeItemIdEmpty",
            errorMessage: "Network Node ItemId is empty",
        },
        "2": {
            constantName: "ENetworkNodeAlreadyExists",
            errorMessage: "Network Node with this ItemId already exists",
        },
        "3": {
            constantName: "ENetworkNodeNotAuthorized",
            errorMessage: "Network Node access not authorized",
        },
        "4": {
            constantName: "EAssemblyAlreadyConnected",
            errorMessage: "Assembly is already connected to this network node",
        },
        "5": {
            constantName: "EAssemblyNotConnected",
            errorMessage: "Assembly is not connected to this network node",
        },
        "6": {
            constantName: "EAssembliesConnected",
            errorMessage: "Assemblies needs to be disconnected before unanchor",
        },
        "7": {
            constantName: "ENetworkNodeOffline",
            errorMessage: "Network Node is offline",
        },
        "8": {
            constantName: "EUnauthorizedSponsor",
            errorMessage: "Unauthorized sponsor",
        },
        "9": {
            constantName: "ETransactionNotSponsored",
            errorMessage: "Transaction not sponsored",
        },
    },
    energy: {
        "0": {
            constantName: "ETypeIdEmpty",
            errorMessage: "Assembly type id cannot be empty",
        },
        "1": {
            constantName: "EInvalidEnergyAmount",
            errorMessage: "Energy amount must be greater than 0",
        },
        "2": {
            constantName: "EIncorrectAssemblyType",
            errorMessage: "Energy requirement for this assembly type is not configured",
        },
        "3": {
            constantName: "EInsufficientAvailableEnergy",
            errorMessage: "Insufficient available energy",
        },
        "4": {
            constantName: "EInvalidMaxEnergyProduction",
            errorMessage: "Max energy production must be greater than 0",
        },
        "5": {
            constantName: "ENotProducingEnergy",
            errorMessage: "Energy source is currently not producing energy",
        },
        "6": {
            constantName: "EProducingEnergy",
            errorMessage: "Energy source is already producing energy",
        },
    },
    fuel: {
        "0": {
            constantName: "ETypeIdEmtpy",
            errorMessage: "Fuel Type Id cannot be empty",
        },
        "1": {
            constantName: "EInvalidFuelEfficiency",
            errorMessage: "Invalid Fuel Efficiency",
        },
        "2": {
            constantName: "EIncorrectFuelType",
            errorMessage: "Fuel Efficiency for this fuel type is not configured",
        },
        "3": {
            constantName: "EInsufficientFuel",
            errorMessage: "Insufficient fuel quantity",
        },
        "4": {
            constantName: "EInvalidDepositQuantity",
            errorMessage: "Deposit quantity must be greater than 0",
        },
        "5": {
            constantName: "EInvalidWithdrawQuantity",
            errorMessage: "Withdraw quantity must be greater than 0",
        },
        "6": {
            constantName: "EFuelCapacityExceeded",
            errorMessage: "Fuel capacity would be exceeded",
        },
        "7": {
            constantName: "EInvalidMaxCapacity",
            errorMessage: "Fuel max capacity must be greater than 0",
        },
        "8": {
            constantName: "EInvalidVolume",
            errorMessage: "Fuel volume must be greater than 0",
        },
        "9": {
            constantName: "EFuelTypeMismatch",
            errorMessage: "Cannot deposit fuel of different type. Withdraw existing fuel first",
        },
        "10": {
            constantName: "EInvalidBurnRate",
            errorMessage: "Burn rate must be at least the minimum configured burn rate",
        },
        "11": {
            constantName: "EFuelNotBurning",
            errorMessage: "Fuel is not currently burning",
        },
        "12": {
            constantName: "EFuelAlreadyBurning",
            errorMessage: "Fuel is already burning",
        },
        "13": {
            constantName: "ENoFuelToBurn",
            errorMessage: "No fuel available to burn",
        },
    },
    inventory: {
        "0": {
            constantName: "ETypeIdEmpty",
            errorMessage: "Type ID cannot be empty",
        },
        "1": {
            constantName: "EInventoryInvalidCapacity",
            errorMessage: "Inventory Capacity cannot be 0",
        },
        "2": {
            constantName: "EInventoryInsufficientCapacity",
            errorMessage: "Insufficient capacity in the inventory",
        },
        "3": {
            constantName: "EItemDoesNotExist",
            errorMessage: "Item not found",
        },
        "4": {
            constantName: "EInventoryInsufficientQuantity",
            errorMessage: "Insufficient quantity in inventory",
        },
    },
    location: {
        "0": {
            constantName: "ENotInProximity",
            errorMessage: "Structures are not in proximity",
        },
        "1": {
            constantName: "EInvalidHashLength",
            errorMessage: "Invalid length for SHA256",
        },
        "2": {
            constantName: "EUnverifiedSender",
            errorMessage: "The proof was not signed for the sender",
        },
        "3": {
            constantName: "EInvalidLocationHash",
            errorMessage: "Invalid location hash",
        },
        "4": {
            constantName: "EUnauthorizedServer",
            errorMessage: "Message signed by unauthorized server",
        },
        "5": {
            constantName: "ESignatureVerificationFailed",
            errorMessage: "Signature verification failed",
        },
        "6": {
            constantName: "EDeadlineExpired",
            errorMessage: "Deadline has expired",
        },
        "7": {
            constantName: "EInvalidDistance",
            errorMessage: "Invalid Distance",
        },
    },
    status: {
        "0": {
            constantName: "EAssemblyInvalidStatus",
            errorMessage: "Assembly status is invalid",
        },
    },
};

/**
 * Gets the error constant name for a given module and error code
 */
export function getErrorConstantName(moduleName: string, errorCode: number): string | undefined {
    return ERROR_MAP[moduleName]?.[errorCode]?.constantName;
}

/**
 * Gets the error message for a given module and error code
 */
export function getErrorMessage(moduleName: string, errorCode: number): string | undefined {
    return ERROR_MAP[moduleName]?.[errorCode]?.errorMessage;
}

/**
 * Gets both the error constant name and message for a given module and error code
 */
export function getErrorInfo(
    moduleName: string,
    errorCode: number
): { constantName: string; errorMessage: string } | undefined {
    return ERROR_MAP[moduleName]?.[errorCode];
}
